# Exported from Render on 2026-09-15T16:22:17Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: it-inventory-app
      runtime: node
      repo: https://github.com/pinkcodingmuscle/it-inventory-app
      plan: 0.5c-512mb
      region: oregon
      buildCommand: npm ci --include=dev && npm run build
      startCommand: npm start
      preDeployCommand: npm run db:migrate
      healthCheckPath: /api/health
      autoDeployTrigger: commit
      rootDir: server
